### ISSUE TITLE
Haml elements with multi words separated by '-' do not highlight correctly

### ISSUE THREAD

**Issue by Jerome67000** [cannikin/language-haml#33]
Hi,

When i use a framework like Ionic, the highlight element with multi words stop after the first word :

![untitled](https://cloud.githubusercontent.com/assets/7358899/7470062/205032dc-f31a-11e4-93cb-2c5351704da1.png)

**Comment by guiiruiz** [comment]
@Jerome67000 I was having the same issue as you and I fixed it.
For the moment you can find the solution here #35.

**Comment by Jerome67000** [comment]
Wow thanks for the hack, its works fine ;)
